name: chas-group-3

services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - "5173:5173"
    command: npm run dev:web
    volumes:
      - .:/app
      - /app/node_modules
      - turbo_cache:/app/.turbo
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - FORCE_COLOR=1
    stdin_open: true
    tty: true

  mobile:
    build: .
    platform: linux/amd64
    ports:
      - "5174:5174"
    command: npm run dev:mobile
    volumes:
      - .:/app
      - /app/node_modules
      - turbo_cache:/app/.turbo
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - FORCE_COLOR=1
    stdin_open: true
    tty: true

  frontend:
    build: .
    platform: linux/amd64
    ports:
      - "5173:5173"
      - "5174:5174"
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - turbo_cache:/app/.turbo
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - FORCE_COLOR=1
    stdin_open: true
    tty: true

volumes:
  turbo_cache:
